// Exercise production attachment RPCs through the normal local Chrome UI, including stored replay.
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {login} from './localBooks.ts';
const root='/tmp/family-upstream-go-books';
const route=JSON.parse(readFileSync(root+'/opus-ui-route.json','utf8'));
const {chromium}=createRequire('/Users/kazuph/node_modules/playwright-core/package.json')('playwright-core');
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage();
const result={logs:[],errors:[]};
page.on('console',m=>result.logs.push({type:m.type(),text:m.text()}));
page.on('pageerror',e=>result.errors.push(e.message));
const select=async name=>{await page.getByRole('button',{name:'Select model',exact:true}).click();await page.getByRole('menuitem',{name,exact:true}).click();};
try{
 await login(page,{base:route.url,username:route.username,password:'LegacyBookUi-20261005'});
 await page.goto(`${route.url}/workspace/${route.workspace}?w=${route.gadget}`);
 await page.getByText('New Chat',{exact:true}).first().waitFor();
 await select('GLM-5.3 Flash (OpenCode Go)');
 await page.locator('input[type="file"]').setInputFiles(root+'/export-firefox-old-book.pdf');
 await page.getByText('Failed',{exact:true}).waitFor();
 result.completionsPdfRejected=true;
 await page.getByRole('button',{name:'Remove attachment',exact:true}).click();
 await select('muse-spark-1.3-contributor (OpenCode Go)');
 await page.locator('input[type="file"]').setInputFiles(root+'/export-firefox-old-book.pdf');
 await page.getByRole('button',{name:'Remove attachment',exact:true}).waitFor();
 await page.getByText('Uploading',{exact:true}).waitFor({state:'hidden'});
 await page.getByRole('combobox').fill('PDF protocol capability check.');
 await page.getByRole('button',{name:'Send message',exact:true,disabled:false}).waitFor();
 assert.equal(await page.getByText('Failed',{exact:true}).count(),0);
 result.responsesPdfUploaded=true;
 await page.getByRole('button',{name:'Remove attachment',exact:true}).click();
 await select('No agent');
 await page.locator('input[type="file"]').setInputFiles(root+'/opus-existing-avatar.webp');
 await page.getByRole('button',{name:'Remove attachment',exact:true}).waitFor();
 await page.getByText('Uploading',{exact:true}).waitFor({state:'hidden'});
 await page.getByRole('combobox').fill('Keep this existing image in the conversation history.');
 await page.getByRole('button',{name:'Send message',exact:true,disabled:false}).click();
 await page.getByRole('button',{name:'Back to conversations',exact:true}).waitFor();
 await page.getByText('Keep this existing image in the conversation history.',{exact:true}).waitFor();
 await page.reload();
 await page.getByText('Keep this existing image in the conversation history.',{exact:true}).waitFor();
 result.nonGoImageHistoryPreserved=true;
 await select('DeepSeek V4 Flash (OpenCode Go)');
 await page.getByRole('combobox').fill('Replay the preceding conversation.');
 await page.getByRole('button',{name:'Send message',exact:true,disabled:false}).click();
 await page.getByText(/The selected OpenCode Go model does not support this attachment type/).first().waitFor();
 result.replayFailure=await page.locator('body').innerText();
 await page.reload();
 await page.getByText(/The selected OpenCode Go model does not support this attachment type/).first().waitFor();
 result.replayFailurePersisted=true;
 await page.screenshot({path:root+'/opus-media-replay.png',fullPage:true});
}catch(e){result.failure={message:e.message,stack:e.stack};result.aria=await page.locator('body').ariaSnapshot();process.exitCode=1;}
finally{writeFileSync(root+'/opus-media-replay.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();}
