import {env,SELF} from 'cloudflare:test';
import {expect,it} from 'vitest';
import type {OverseerDurableObject} from './test-worker';
const decode=(v:any):any=>v?.$date?new Date(v.$date):v?.$bytes?Uint8Array.fromBase64(v.$bytes):Array.isArray(v)?v.map(decode):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,decode(x)])):v;
const lookup=(state:any,key:string)=>state.kv.find(([name]:[string])=>name===key);

it('real signed Access admin reads root and cold facet without mutation or executing application constructor',async()=>{
  const bindings=env as unknown as {MAINTENANCE_TEST:DurableObjectNamespace<OverseerDurableObject>;MAINTENANCE_JWKS:string};
  const tokens=await(await fetch(bindings.MAINTENANCE_JWKS+'/tokens')).json() as Record<string,string>;
  const root=bindings.MAINTENANCE_TEST.getByName('existing-root');
  await root.seed();
  const url='https://maintenance.test/maintenance/inspect?class=OverseerDurableObject&id='+root.id;
  const get=(token?:string,path=url,method='GET')=>SELF.fetch(path,{method,headers:token?{'cf-access-jwt-assertion':token}:{}});
  for(const token of [undefined,tokens.other,tokens.service,tokens.wrongKey,tokens.wrongIssuer,tokens.wrongAudience,tokens.expired])expect((await get(token)).status).toBe(403);
  expect((await get(tokens.admin,url,'POST')).status).toBe(405);
  const first=await get(tokens.admin);expect(first.status).toBe(200);expect(first.headers.get('cache-control')).toBe('no-store');
  const before=await first.json();
  expect(JSON.stringify(before)).toContain('opaque-preserved-in-namespace');
  expect(JSON.stringify(before)).not.toContain('retained-credential');
  const facetResponse=await get(tokens.admin,url+'&gadget=7');expect(facetResponse.status).toBe(200);
  const facet=await facetResponse.json() as {facetName:string;tables:Array<{name:string;rows:unknown[]}>};
  expect(facet.facetName).toBe('gadget');
  expect(facet.tables.find(t=>t.name==='constructor_runs')!.rows).toHaveLength(1);
  expect(JSON.stringify(facet)).toContain('Preserved manuscript');
  expect(JSON.stringify(facet)).toContain('opaque-preserved-in-namespace');
  await expect(get(tokens.admin,url+'&gadget=99')).rejects.toThrow('Gadget is absent from the stored registry');
  expect(await(await get(tokens.admin)).json()).toEqual(before);
  expect(await root.checkAuthority()).toEqual({value:'retained-credential',calls:1});
  expect(await(await get(tokens.admin,url+'&gadget=7')).json()).toEqual(facet);
});

it('converts actual deployed-runtime Yjs without losing accepted/draft history and rolls back actual persistence failure',async()=>{
  const bindings=env as unknown as {CONVERSION_TEST:DurableObjectNamespace<import('./test-worker').ConversionFixture>;MAINTENANCE_LIVE_FIXTURE:string};
  if(!bindings.MAINTENANCE_LIVE_FIXTURE)throw new Error('MAINTENANCE_LIVE_FIXTURE must be generated by the recognized live runtime');
  const captured=JSON.parse(bindings.MAINTENANCE_LIVE_FIXTURE);
  const rows=decode(captured.kv) as Array<[string,unknown]>;
  const owner=new Map(rows).get('ownerId') as string;
  const root=bindings.CONVERSION_TEST.getByName('actual-live-migration');await root.seed(rows);
  const original=await root.inspect();
  console.log('native PITR availability:',await root.probeBookmark());
  expect(await root.tryConvert('unrecognized-source',owner)).toEqual({ok:false,error:'Error: Unrecognized deployed source'});
  expect(await root.tryConvert(captured.sourceSha256,'wrong-owner')).toEqual({ok:false,error:'Error: Workspace owner mismatch'});
  expect(await root.inspect()).toEqual(original);
  const failure=await root.failAfterConvert(captured.sourceSha256,owner);expect(failure.failed).toBe(true);expect(failure.error).toContain('could not be cloned');
  expect(await root.inspect()).toEqual(original);
  expect((await root.convert(captured.sourceSha256,owner)).status).toBe('converted');
  const migrated=await root.migrated(captured.gadgetId,captured.chatId);
  expect(migrated.files).toEqual([['README.md','Accepted live-schema manuscript']]);
  expect(migrated.meta?.codeBase).toBeDefined();
  expect(JSON.stringify(migrated.messages)).toContain('with pending edit');
  const after=await root.inspect();expect(await root.convert(captured.sourceSha256,owner)).toEqual({status:'noop'});expect(await root.inspect()).toEqual(after);
  expect(lookup(after,'ownerId')).toEqual(lookup(original,'ownerId'));
  for(const [key,value] of original.kv){if(key.startsWith('code:'))expect(lookup(after,key)).toEqual([key,value]);}
  expect(original.tables).toEqual(after.tables);
  expect(await root.checkAuthority()).toEqual({value:'retained-credential',calls:1});
});

it('rejects unsupported persisted workspace states before changing any stored value',async()=>{
  const bindings=env as unknown as {CONVERSION_TEST:DurableObjectNamespace<import('./test-worker').ConversionFixture>;MAINTENANCE_LIVE_FIXTURE:string};
  if(!bindings.MAINTENANCE_LIVE_FIXTURE)throw new Error('A recognized live-runtime fixture is required');
  const captured=JSON.parse(bindings.MAINTENANCE_LIVE_FIXTURE);
  const variants=[
    {name:'unknown-version',prefix:'version',change:()=>3,error:'Not recognized legacy Yjs version 2'},
    {name:'pruned',prefix:'snapshotParts:',change:()=>({parts:[]}),error:'Pruned partitioned history'},
    {name:'moved',prefix:'gadgets:',change:(value:any)=>({...value,move:{}}),error:'Moved workspace'},
    {name:'active',prefix:'chatMeta:',change:(value:any)=>({...value,activeAgent:'persisted-agent'}),error:'Workspace has an active agent'},
  ];
  for(const variant of variants){
    const rows=decode(captured.kv) as Array<[string,unknown]>;
    const match=rows.find(([key])=>key.startsWith(variant.prefix));
    if(variant.name==='pruned')rows.push(['snapshotParts:fixture',variant.change()]);
    else{
      if(!match)throw new Error('Fixture lacks required '+variant.prefix);
      match[1]=variant.change(match[1]);
    }
    const root=bindings.CONVERSION_TEST.getByName('stop-'+variant.name);
    await root.seed(rows);
    const before=await root.inspect();
    const result=await root.tryConvert(captured.sourceSha256,new Map(rows).get('ownerId') as string);
    expect(result.ok).toBe(false);expect(result.error).toContain(variant.error);
    expect(await root.inspect()).toEqual(before);
  }
});
