import { DurableObject } from 'cloudflare:workers';
import { COMPATIBILITY_DATE } from '@gadgets/scripts/worker-config';
import { MaintenanceRoot } from './read-only';
export * from './worker';
export {default} from './worker';

/** Real local stored authority; maintenance must neither call it nor replace it. */
export class StoredAuthority extends DurableObject {
  /** Read/write methods exist only in this local fixture's service. */
  read() {this.ctx.storage.kv.put('reads',Number(this.ctx.storage.kv.get('reads'))+1);return this.ctx.storage.kv.get('value');}
  /** Seed isolated authority state. */
  seed() {this.ctx.storage.kv.put('value','retained-credential');this.ctx.storage.kv.put('reads',0);}
  /** Verify maintenance never called the authority. */
  count() {return this.ctx.storage.kv.get('reads');}
}

/** Represents a real dynamic application constructor with observable writes. */
export class ApplicationFacet extends DurableObject {
  constructor(ctx:DurableObjectState,env:Cloudflare.Env) {
    super(ctx,env);
    ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS constructor_runs(count INTEGER)');
    ctx.storage.sql.exec('INSERT INTO constructor_runs VALUES (1)');
  }
  /** Persist actual SQLite manuscript/progress/history/settings and an authority. */
  seed(authority:unknown) {
    this.ctx.storage.sql.exec('CREATE TABLE book_files(path TEXT PRIMARY KEY, content TEXT)');
    this.ctx.storage.sql.exec("INSERT INTO book_files VALUES ('chapter.md','Preserved manuscript')");
    this.ctx.storage.kv.put('authority',authority);
  }
}

/** Test-only data generation, not an authentication or production maintenance write endpoint. */
export class OverseerDurableObject extends MaintenanceRoot {
  /** Generate real root/facet/opaque state once, then evict the application facet. */
  async seed() {
    if([...this.ctx.storage.kv.list()].length)throw new Error('Fixture requires empty storage');
    const exports=this.ctx.exports as typeof this.ctx.exports & {
      StoredAuthority:DurableObjectNamespace<StoredAuthority>;
      ApplicationFacet:DurableObjectClass<ApplicationFacet>;
    };
    const authority=exports.StoredAuthority.getByName('stored-authority');
    await authority.seed();
    this.ctx.storage.kv.put('ownerId','unchanged-owner');
    this.ctx.storage.kv.put('version',2);
    this.ctx.storage.kv.put('defaultGadgetId',7);
    this.ctx.storage.kv.put('gadgets:0000000000000007',{id:7,output:{id:'book'}});
    this.ctx.storage.kv.put('authority',{nested:authority});
    this.ctx.storage.kv.put('draft',new Uint8Array([1,2,3]));
    await this.ctx.storage.setAlarm(new Date('2099-01-01T00:00:00Z'));
    const loader=(this.env as {LOADER:WorkerLoader}).LOADER;
    const worker=loader.get('real-maintenance-application-fixture',()=>({
      compatibilityDate:COMPATIBILITY_DATE,
      compatibilityFlags:['allow_irrevocable_stub_storage'],
      mainModule:'gadget.js',
      modules:{'gadget.js':{js:`import {DurableObject} from 'cloudflare:workers';
        export class Gadget extends DurableObject {
          constructor(ctx,env){super(ctx,env);ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS constructor_runs(count INTEGER)');ctx.storage.sql.exec('INSERT INTO constructor_runs VALUES (1)');}
          seed(authority){this.ctx.storage.sql.exec('CREATE TABLE book_files(path TEXT PRIMARY KEY,content TEXT)');this.ctx.storage.sql.exec("INSERT INTO book_files VALUES ('chapter.md','Preserved manuscript')");this.ctx.storage.kv.put('authority',authority);}
        }`}},
      globalOutbound:null,
    }));
    const facet=this.ctx.facets.get('gadget',()=>({class:worker.getDurableObjectClass<ApplicationFacet>('Gadget'),id:'gadget'}));
    await facet.seed(authority);
    this.ctx.facets.abort('gadget',new Error('Stop application code before maintenance'));
  }
  /** Prove stored authority still reaches exactly the same real service after inspect. */
  async checkAuthority() {
    const value=this.ctx.storage.kv.get<{nested:Fetcher<StoredAuthority>}>('authority');
    return {value:await value!.nested.read(),calls:await value!.nested.count()};
  }
}

/** Isolated migration target; writes here cannot be reached through maintenance HTTP. */
export class ConversionFixture extends MaintenanceRoot {
  /** Restore data generated by the recognized actual live runtime into empty test storage. */
  async seed(rows:Array<[string,unknown]>) {
    if([...this.ctx.storage.kv.list()].length)throw new Error('Empty isolated target required');
    const exports=this.ctx.exports as typeof this.ctx.exports & {StoredAuthority:DurableObjectNamespace<StoredAuthority>};
    const authority=exports.StoredAuthority.getByName('conversion-authority');await authority.seed();
    this.ctx.storage.transactionSync(()=>{
      for(const[key,value]of rows)this.ctx.storage.kv.put(key,value);
      this.ctx.storage.kv.put('preservedAuthority',authority);
    });
  }
  /** Exercise the same persisted authority after converting code only. */
  async checkAuthority(){const authority=this.ctx.storage.kv.get<Fetcher<StoredAuthority>>('preservedAuthority')!;return {value:await authority.read(),calls:await authority.count()};}
  /** Record actual local PITR availability, never claim an emulated bookmark as native recovery. */
  async probeBookmark(){try{return {supported:true,bookmark:await this.bookmark()};}catch(error){return {supported:false,error:String(error)};}}
  /** Apply the real pre-converter and expose the new tree without starting the application. */
  async convert(source:string,ownerId:string) {
    const {convertRecognizedWorkspace}=await import('./convert');
    return await convertRecognizedWorkspace(this.ctx,source,ownerId);
  }
  /** Report the actual rejected converter call within the DO, avoiding test RPC rejection bookkeeping. */
  async tryConvert(source:string,ownerId:string) {
    try {return {ok:true,result:await this.convert(source,ownerId)};}catch(error){return {ok:false,error:String(error)};}
  }
  /** Cause an actual serializer failure after conversion within an enclosing transaction. */
  async failAfterConvert(source:string,ownerId:string) {
    try {await this.ctx.storage.transaction(async()=>{
      const{convertRecognizedWorkspace}=await import('./convert');
      await convertRecognizedWorkspace(this.ctx,source,ownerId);
      this.ctx.storage.kv.put('invalid-maintenance-publication',()=>{});
    });return {failed:false};}catch(error){return {failed:true,error:String(error)};}
  }
  /** Read migrated accepted files and the retained draft change stream. */
  async migrated(gadgetId:number,chatId:number) {
    const{makeOverseerStorage}=await import('../../src/storage-schema/overseer-storage');
    const{GitStore}=await import('../../src/git-store');
    const storage=makeOverseerStorage(this.ctx.storage);const git=new GitStore(storage.gitObjects);
    const gadget=storage.gadgets.get(gadgetId)!;
    if(gadget.type!=='gadget')throw new Error('Expected migrated gadget');
    return {gadget,meta:storage.chatMeta.get(chatId),files:[...await git.readCommitFiles(gadget.commitId!)],messages:[...storage.chats.list()].filter(message=>message.chatId===chatId)};
  }
}
